base_model: mistralai/Mistral-7B-Instruct-v0.1
model_type: MistralForCausalLM
tokenizer_type: LlamaTokenizer
is_mistral_derived_model: true

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: pretokenized_finetuning_data.jsonl
    ds_type: json
    type: completion
# dataset_prepared_path: last_run_prepared
val_set_size: 0.02
output_dir: ./finetuned-out

sequence_len: 8192
sample_packing: false
eval_sample_packing: false
pad_to_sequence_len: false

adapter:
# lora_r: 32
# lora_alpha: 16
# lora_dropout: 0.05
# lora_target_modules:
# lora_target_linear: true
# lora_fan_in_fan_out:

wandb_project: mistral-7b-qft-textbook-full-finetuning
wandb_entity:
wandb_watch: gradients
wandb_run_id:
wandb_log_model:

gradient_accumulation_steps: 8
micro_batch_size: 2
num_epochs: 3
optimizer: adamw_torch
adam_beta1: 0.9
adam_beta2: 0.95
lr_scheduler: cosine
learning_rate: 0.000001
max_grad_norm: 1.0

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true

early_stopping_patience:
resume_from_checkpoint: 
auto_resume_from_checkpoints:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
logging_steps: 1
eval_steps: 0.05
save_steps:
debug:
deepspeed:
weight_decay: 0.0
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"
  pad_token: "</s>"

# FSDP
fsdp:
fsdp_config:
